//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penzugyi_tanacsado
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllData
    {
        public Nullable<System.DateTime> TalálkozóDátuma { get; set; }
        public string TalálkozóKezdésiIdőpontja { get; set; }
        public string ÜgyfélNeve { get; set; }
        public string TanácsadóNeve { get; set; }
        public string SzakterületMegnevezése { get; set; }
        public Nullable<int> TalálkozóIdőtartama { get; set; }
        public Nullable<int> TanácsadóÓradíja { get; set; }
        public string TalálkozóértFizetendőÖsszeg { get; set; }
    }
}
