//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penzugyi_tanacsado
{
    using System;
    using System.Collections.Generic;
    
    public partial class talalkozo
    {
        public int talalkozo_id { get; set; }
        public Nullable<int> tanacsado_id { get; set; }
        public Nullable<int> ugyfel_id { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<System.TimeSpan> idopont { get; set; }
        public Nullable<int> idotartam { get; set; }
    
        public virtual tanacsado tanacsado { get; set; }
        public virtual ugyfel ugyfel { get; set; }
    }
}
