//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penzugyi_tanacsado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tanacsadoEntities4 : DbContext
    {
        public tanacsadoEntities4()
            : base("name=tanacsadoEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<szakterulet> szakterulet { get; set; }
        public DbSet<talalkozo> talalkozo { get; set; }
        public DbSet<tanacsado> tanacsado { get; set; }
        public DbSet<ugyfel> ugyfel { get; set; }
        public DbSet<AllData> AllData { get; set; }
    }
}
