//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penzugyi_tanacsado
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanacsado
    {
        public tanacsado()
        {
            this.talalkozo = new HashSet<talalkozo>();
        }
    
        public int tanacsado_id { get; set; }
        public string nev { get; set; }
        public Nullable<int> szakterulet_id { get; set; }
        public Nullable<int> oradij { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
    
        public virtual szakterulet szakterulet { get; set; }
        public virtual ICollection<talalkozo> talalkozo { get; set; }
    }
}
